### ISSUE TITLE
Pause function

### ISSUE THREAD

**Issue by juri74** [sweetlilmre/tapuino#10]
Could be possible to implement a pause button? example: using the "select" button during tape play, pressing it will pause tape and pressing it again will unpause tape.
this would be useful with tapes that have more programs/games in it

**Comment by sweetlilmre** [comment]
How common is this? A higher priority would be proper seek control for multipart games, which would probably provide you with what you needed for this feature.

**Comment by sweetlilmre** [comment]
I've added experimental support for this in the pause-func branch. Test and I'll think about merging it into master as a temporary fix until proper play control is added

**Comment by sweetlilmre** [comment]
This is now in master
