### ISSUE TITLE
Error in header of saved c16 .tap files

### ISSUE THREAD

**Issue by juri74** [sweetlilmre/tapuino#12]
When saving from C16 (and presumibly Plus4) is generated a C64 tap header, this preventing loading the tap files into winvice emulator. loaction $0D of the header does contain $00 value, this location should contain $02 value, like all c16 tap files i examined. manually changing the value from $00 to $02 (with the help of an hex editor) fixed the problem and tape loaded successfully in winvice

**Comment by sweetlilmre** [comment]
This has been fixed.
