### ISSUE TITLE
Recordings are finalized when motor stops

### ISSUE THREAD

**Issue by Quagliarulo** [sweetlilmre/tapuino#18]
Hello, I have a proposal. Tapuino shouldn't finalize a recording when the motor is turned off. It should just wait for either the motor to be started again or the user to press "stop". I'm playing with the Freeload mastering tool. It loads each file from disk and then stores it on tape. But it doesn't work with Tapuino, because when the program stops the motor and reads from disk, the recording is finalized.

**Comment by sweetlilmre** [comment]
I have added a branch to test this as a new feature.
Under the options menu there is an "Auto Finalize" option. If this is set to zero then the recording will continue until the ABORT button is pressed. Please test and let me know if this addresses the issue.

**Comment by Quagliarulo** [comment]
Hello and thank you for your time. Your modification addresses the issue. Here's a freeload game mastered with Tapuino:
https://drive.google.com/file/d/0Bzow0Exbi92AeW5IQ2RHcUFyNnc/view?usp=sharing

Some thoughts:
- A couple of times I had lockups while browsing through the menus, with a strange string:
  https://drive.google.com/file/d/0Bzow0Exbi92AeXdZRlJjUzl5Ylk/view?usp=sharing
  I guess this might be due to some "unexpected" button presses I made (I connected my button panel incorrectly and wouldn't bother to fix it). I'll try to replicate it.
- "Auto di finalizzazione" should become "Auto finalizza" (how do I know? I'm Italian :)
- I think the spinning character shouldn't spin when the motor is off
- The message "Aborted" / "Annullato" is somewhat misleading in this case. Don't know... Maybe "Stopped" / "Fermato"?

**Comment by Quagliarulo** [comment]
I just noticed there are very long pauses between freeload blocks. This doesn't happen with Vice (no pauses at all in that case). Gotta try with real tape.

**Comment by Quagliarulo** [comment]
Real tape mastered and dumped with MTAP. Tapclean says pauses between Freelod blocks are either 1.0556 or 1.0759 seconds, so I'm afraid something doesn't work.

**Comment by sweetlilmre** [comment]
I've added another commit to try and address the pausing issue as well as the menu bug introduced by the previous commit. Please test!

**Comment by sweetlilmre** [comment]
closed due to inactivity
