### ISSUE TITLE
Repository language incorrectly classified 

### ISSUE THREAD

**Issue by wbuchanan** [sweetlilmre/tapuino#28]
Project classified as Stata repo on GitHub, but repository does not appear to include any code related to the Stata language.  Please correct the language classification for your project.  It will help make your project more visible where it should be and will avoid coming up in searches for Stata projects for others.

**Comment by sweetlilmre** [comment]
Thanks, although this seems to be an automated classification by github. Is there a simple way to change it?

**Comment by wbuchanan** [comment]
You’d need to create a `.gitattributes` file and could then override the linguist settings that end up leading it to classify the repo as a Stata repo.

**Comment by sweetlilmre** [comment]
Thanks for the tip. This has been corrected now and the project shows as "C" as it should
