### ISSUE TITLE
Porting to Mega 2560 : problem after "found" message

### ISSUE THREAD

**Issue by dashiad** [sweetlilmre/tapuino#29]
I'm mixing your code with some iec code i've developed, to have both tape and disk support.
As the code for the disk may grow (a lot), and i've added a touchscreen, i've chosen a mega 2560 as target device.
But i'm getting a bit stuck with a problem: the load starts ok, but, after the "found xxx" message appears, looks like somewhere is not detecting the play button as pressed anymore: after the "found" message, i get a "LOADING" and then,again, "PRESS PLAY ON TAPE".

Any idea of what may be happening? (I ported the code to a mega 1280 without problems)
My pin assignment is (even pins from 35 to 41):

// port definitions, change for different wiring
#define SENSE_PORT          PORTG
#define SENSE_DDR           DDRG
#define SENSE_PIN           0
#define SENSE_ON()          SENSE_PORT &= ~_BV(SENSE_PIN)
#define SENSE_OFF()         SENSE_PORT |=  _BV(SENSE_PIN)

#define TAPE_READ_PORT      PORTC
#define TAPE_READ_DDR       DDRC
#define TAPE_READ_PIN       0
#define TAPE_READ_PINS      PINC
#define TAPE_READ_LOW()     TAPE_READ_PORT &= ~_BV(TAPE_READ_PIN)
#define TAPE_READ_HIGH()    TAPE_READ_PORT |=  _BV(TAPE_READ_PIN)

#define TAPE_WRITE_PORT     PORTG
#define TAPE_WRITE_DDR      DDRG
#define TAPE_WRITE_PINS     PING
#define TAPE_WRITE_PIN      2

#define MOTOR_PORT          PORTC
#define MOTOR_DDR           DDRC
#define MOTOR_PIN           2
#define MOTOR_PINS          PINC
#define MOTOR_IS_OFF()      (MOTOR_PINS & _BV(MOTOR_PIN))

**Comment by juri74** [comment]
that's very curious.
have you tried different taps? have you tried to load the same tap with a real datassette?
that sound very strange because as soon as "found" message appear, when you press space or commodore key even if you have stopped the datassette, the c64 should behave like if the play button is pressed (even if it isn't)

**Comment by dashiad** [comment]
I've been debugging a bit more.
What i've found is : tapuino thinks the tape has finished  
(g_tap_file_pos == g_tap_info.length) (line 225 of tapuino.c). 
Looks like something is messing with the timer, maybe the lcd code. I'll try using timer 3 instead 1 to see if that helps.

But at least i've a hint about what is wrong with my code, (of course, it's not tapuino's fault), so i'm closing the issue. Thanks for your help!
