### ISSUE TITLE
Low memory warnings 

### ISSUE THREAD

**Issue by gwiorek** [sweetlilmre/tapuino#32]
Is this normal?  First time working with the code part of tapunio and a bit rusty with the Arduino but seems to be a big possible issue should you have more the a few tape files to track. 

![image](https://user-images.githubusercontent.com/11354599/58397327-0dc28b00-8016-11e9-9151-bbd68b64e6a9.png)

Trying to reimage my mini as it jsut stopped working and trying to resurrect it as it looks like the nano may be still working but lost the software.

**Comment by sweetlilmre** [comment]
This is fine, the sketch is just almost at max capacity for the nano.

**Comment by gwiorek** [comment]
Thanks!  


-----Original Message-----
