### ISSUE TITLE
The Max7219.h library

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [sweetlilmre/tapuino#34]
Hello i was looking at the code and say there is a Max7219.h in the arduino ino. But in your files you do not have have the libray there. I don't know that library either. I know the Max7219 chip is a input/output driver for leds. But yet somehow the code compiles with no problem even if i don't have that library. Strage!! 

I never saw a code  compile with no errors with a missing library. Why is this?

Joseph

**Comment by sweetlilmre** [comment]
Hi,

I don't see this in the .ino file?

**Comment by Therealjosephchrzempiec** [comment]
I'm  sorry that was the sd2iec i was looking at my mistake.

**Comment by sweetlilmre** [comment]
No worries :-)

**Comment by Therealjosephchrzempiec** [comment]
I just tried tapuino for the first time tonight and went great
 I hand build my own becuase i cant afford to buy one. But it took me a while to figure out the wiring. Used a lot of jumper wires lol.
