### ISSUE TITLE
Not a issue but I have a question

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [sweetlilmre/tapuino#35]
Hello you did a awesome Job on the tapuino for arduino. It works great, Thank you.  But i have a question have you looked into maybe doing the sd2iec? I know there out there  but not a arduino version. 

Joseph

**Comment by sweetlilmre** [comment]
The arduino doesn't have enough power to handle sd2iec.
I did look at it once. Better bet would be a cheap arm board

**Comment by Therealjosephchrzempiec** [comment]
Hello thank you.  Is there a better way to get a message to you without taking up issues in here?

**Comment by sweetlilmre** [comment]
Email? My username at Gmail.
