### ISSUE TITLE
Possibe bug while reading the tape buffer?

### ISSUE THREAD

**Issue by dashiad** [sweetlilmre/tapuino#38]
Hello,
For a small project i'm working in, i want to refactor some code out of the interrupt handler, specially calculating the pulse lengths in the main loop. That would produce a mismatch between the number of bytes read from the file, and the number of pulses to fire, as "overflow" bytes need 4 bytes if the version is not 0.
So, theoretically,  to correctly convert  X bytes from the file to pulses, i need to be sure the buffer grows, if necessary, up to X+3 bytes, in case the last byte read is 0x00 (overflow byte), and version is not 0.
So i went to check how this is managed in tapuino, but (correct me if i'm wrong) looks like a fixed chunk of  FAT_BUF_SIZE bytes are read, and the isr code is supposing that, if a 0x00 byte is found, the other 3 bytes do exist in the buffer 
```
 if (tap_data != 0) {
          g_pulse_length_save = tap_data * g_cycle_mult_8;
        } else {
          g_pulse_length_save =  (unsigned long) g_fat_buffer[g_read_index++];
          g_pulse_length_save |= ((unsigned long) g_fat_buffer[g_read_index++]) << 8;
          g_pulse_length_save |= ((unsigned long) g_fat_buffer[g_read_index++]) << 16;
         ...
   }
``` 
So, if a 0x00 byte is found at g_fat_buffer[FAT_BUF_SIZE-1], arent those lines accessing unitialized memory?

**Comment by sweetlilmre** [comment]
I think you are correct. Amazingly this doesn't seem to have caused a problem in real life. Even more so as the potentially out of bound bytes are the most significant values of the timing signal and random data could really skew the value.
The issue for me is that the buffer swapping and handling is tightly coupled to the buffer size and would require significant rework to fix. I really need to rewrite this codebase at some point to use a more modern mcu like an ESP.

**Comment by sweetlilmre** [comment]
On further reflection this isn't actually a problem :)
The buffer that the data is read from is a 256 byte buffer, indexed by a byte-wide variable (g_read_index).
Think of the buffer as two 128 byte buffers joined together.
As the longer pulse lengths are computed 1 byte at a time, if the index is 255 it will overflow back to zero.
This is half of the story. What is happening outside of the interrupt is that the buffer index is monitored, as it moves to the 2nd half of the buffer, the first half is filled with an SD load and same as it moves to the first half.
This means that as long as the TAP data is valid, no uninitialized memory is accessed.
