### ISSUE TITLE
utf-8 chars

### ISSUE THREAD

**Issue by inter981** [sweetlilmre/tapuino#46]
Hi!
is it possible to add accented or special latin chars?

i want to translate into portuguese or french, but special latin chars are not allowed.

Thank you.

**Comment by sweetlilmre** [comment]
Hi there,

With the some of supported LCDs, I can only use what is available in the ROM of e.g. the Hitachi displays, so this wouldn't be possible. IIRC one of the supported displays is a bitmap based OLED where the font could possibly be changed to support  special chars, but that would then only work for that specific H/W configuration.

As I am working on the TapuinoNext (https://www.github.com/TapuinoNext) I don't have much time to support this version any more (though I would be happy to look at a pull request). I will look into this support for the TapuinoNext.
