### ISSUE TITLE
Save led, piezo to "listen to" the tape

### ISSUE THREAD

**Issue by juri74** [sweetlilmre/tapuino#7]
Could be possible to implement:
1) a red led that will lit when saving in progress? 
2) a piezo that play the music? :D for ability to listen loading/saving maybe turnable on/off in Options menu ;)
i splitted the pause from led & piezo, since there is an hardware solution is better use it to save program space.. however a led connected to D13 (if isn't used for other things) could be useful and shouldn't use much program memory i think (D13 is already connected to a led on almost all arduinos) :)

**Comment by sweetlilmre** [comment]
There are hardware solutions available for something similar to the piezo via ozayturay's board (provides LEDs that are transistor driven for SAVE / LOAD).
Please could you break this up into separate issues? The save LED could be handled fairly easily via code (just add an output) etc. so tracking these separately is better.

**Comment by sweetlilmre** [comment]
The save LED function will be added with the release of the 1.7 hardware and controlled via software, I'm just waiting for the boards so that I can verify this.
The piezo switching is another story and would require hard ware support so I don't think this is going to happen.

**Comment by juri74** [comment]
Thank you for update, i have an idea on how doing piezo support with minimal effort, i think arduino should provide an "activation signal" then it will be ANDed with the tape read or tape write signal, finally the output pin of the AND chip will drive a piezo. i have to wait the 1.7 board too and some parts for testing :) i lost track of available pins, is there one free? thanks 
Juri

**Comment by sweetlilmre** [comment]
Save LED support has been added to the code base, piezo is hardware supported on 1.7.
