### ISSUE TITLE
C16 / Plus 4 halfwave playback support

### ISSUE THREAD

**Issue by sweetlilmre** [sweetlilmre/tapuino#9]
Adding support for format 2 (halfwave) TAP playback would extend the reach of the Tapuino to these platforms.

**Comment by juri74** [comment]
i tested some v2 (and v1) c16 tap with tapuino without success. when i press select when displaying a tap file name nothing happens (if the file name is scrolling on display the scroll position is resetted to beginning of text every time i press select button)

**Comment by sweetlilmre** [comment]
How recent is the code you have flashed? There was a bug where the C16 TAP file would have been considered invalid but the error would not have been displayed making it look like nothing had happened. This code has changed and C16 support was added for headers a few versions back.
Can you confirm or flash the latest and try again?

**Comment by juri74** [comment]
hello! updated to the most recent version and now it recognize some files (some give INVALID TAP) 
i sent you a report email with attached a zip file containing the TAP files i tested.

**Comment by sweetlilmre** [comment]
Hi. I've updated the source with some fixes, please test when you are back in town.

**Comment by juri74** [comment]
hello
i will test asap :D

Il 21/04/2015 16:47, sweetlilmre ha scritto:

> Hi. I've updated the source with some fixes, please test when you are 
> back in town.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sweetlilmre/tapuino/issues/9#issuecomment-94824684.

---

Questa e-mail è stata controllata per individuare virus con Avast antivirus.
http://www.avast.com

**Comment by juri74** [comment]
I made further test with updated firmware, actually i had a problem only with one file on 19 files tested, i'm going on testing, but it does appear the last firmware update really fixed lot of tap loading problems :)

**Comment by sweetlilmre** [comment]
This code is in now and I have a C16 on order so I will hopefully be able to look into this in more detail once I have the machine :)

**Comment by sweetlilmre** [comment]
closed
